### ISSUE TITLE
the trees spawn in mushroom fields which is inda weird idk

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/mysticaloaktree-multi#3]

**Comment by MehVahdJukaar** [comment]
So can azalea treees

**Comment by thelegitdolt** [comment]
the azalea trees also look really out of place, but they're there to indicate lush caves right. it just doesn't make that much sense that the funny tree is there imo

**Comment by MehVahdJukaar** [comment]
Thing is right now they are set to just spawn everywhere. Not doing so would mean I would have to manually select all the biomes they will spawn in as the game has no way to blacklist stuff like that and I wanted it to work on any modded biome. Also you are kind of right funni tree isn't well akwainted with mushrooms, as he says in a couple of lines

**Comment by thelegitdolt** [comment]
i see
